version: '3.6'

services:
  db:
    env_file:
    - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  backend:
    env_file:
    - .env
    environment:
      - SERVER_TYPE=${SERVER_TYPE}

